openapi: 3.0.3
info:
  title: OpenAPI schema for template deploy-source-code
components:
  schemas:
    variables:
      required:
      - git_url
      - image
      x-walrus-ui:
        groupOrder:
        - Build
        - Deploy
      type: object
      properties:
        git_url:
          title: Git URL
          type: string
          description: URL to the source code repository.
          x-walrus-ui:
            group: Build
            order: 1
        git_branch:
          title: Git Branch
          type: string
          description: Branch of the repository to clone.
          default: main
          x-walrus-ui:
            group: Build
            order: 2
        git_auth:
          title: Git Authentication
          type: boolean
          default: false
          x-walrus-ui:
            group: Build
            order: 3
        git_username:
          title: Git Username
          type: string
          description: Username for cloning the git repository.
          writeOnly: true
          x-walrus-ui:
            group: Build
            order: 4
            showIf: git_auth=true
        git_password:
          title: Git Password
          type: string
          description: Password for cloning the git repository.
          format: password
          writeOnly: true
          x-walrus-ui:
            group: Build
            order: 5
            showIf: git_auth=true
        git_path:
          title: Sub Path
          type: string
          description: Path to the source code.
          x-walrus-ui:
            group: Build
            order: 6
        dockerfile:
          title: Dockerfile Path
          type: string
          description: Path to the Dockerfile.
          default: Dockerfile
          x-walrus-ui:
            group: Build
            order: 7
        registry_auth:
          title: Registry Authentication
          type: boolean
          default: false
          x-walrus-ui:
            group: Build
            order: 8
        registry_username:
          title: Registry Username
          type: string
          description: Username for the image registry.
          writeOnly: true
          x-walrus-ui:
            group: Build
            order: 9
            showIf: registry_auth=true
        registry_password:
          title: Registry Password
          type: string
          description: Password for the image registry.
          format: password
          writeOnly: true
          x-walrus-ui:
            group: Build
            order: 10
            showIf: registry_auth=true
        image:
          title: Image Name
          type: string
          description: Name of the image to be built and deployed.
          x-walrus-ui:
            group: Build
            order: 11
        replicas:
          title: Replicas
          type: number
          description: Count of pods
          default: 1
          x-walrus-ui:
            group: Deploy
            order: 12
        ports:
          title: Ports
          type: array
          description: Service ports to expose
          default:
          - 80
          items:
            type: number
          x-walrus-ui:
            colSpan: 6
            group: Deploy
            order: 13
        request_cpu:
          title: CPU Request
          type: string
          description: CPU request. e.g. 0.5, 1, 2
          default: "0.1"
          x-walrus-ui:
            group: Deploy
            order: 14
        request_memory:
          title: Memory Request
          type: string
          description: Memory request. e.g. 128Mi, 512Mi, 1Gi, 2Gi, 4Gi
          default: 128Mi
          x-walrus-ui:
            group: Deploy
            order: 15
        limit_cpu:
          title: CPU Limit
          type: string
          description: CPU limit. e.g. 0.5, 1, 2
          default: ""
          x-walrus-ui:
            group: Deploy
            order: 16
        limit_memory:
          title: Memory Limit
          type: string
          description: Memory limit. e.g. 128Mi, 512Mi, 1Gi, 2Gi, 4Gi
          default: ""
          x-walrus-ui:
            group: Deploy
            order: 17
        namespace:
          title: Namespace
          type: string
          description: Namespace to deploy. Auto-generated if empty.
          default: ""
          x-walrus-ui:
            group: Deploy
            order: 18
        name:
          title: Deployment Name
          type: string
          description: Name of the deployment resource. Auto-generated if empty.
          default: ""
          x-walrus-ui:
            group: Deploy
            order: 19
        env:
          title: Environment Variables
          type: object
          description: Name and value pairs to set as the environment variables
          default: {}
          additionalProperties:
            type: string
          x-walrus-ui:
            colSpan: 12
            group: Deploy
            order: 20
        context:
          title: Context
          type: object
          description: |
            Receive contextual information. When Walrus deploys, Walrus will inject specific contextual information into this field.

            Examples:
            ```
            context:
              project:
                name: string
                id: string
              environment:
                name: string
                id: string
              resource:
                name: string
                id: string
            ```
          default: {}
          additionalProperties:
            type: object
            x-walrus-ui:
              colSpan: 12
          x-walrus-ui:
            hidden: true
            group: Deploy
            order: 21

